#!/usr/bin/env bash
# Spin up the GuildedThorn dev environment:
#   MongoDB + RabbitMQ in containers, .env with dev secrets, seeded test data.
# Usage: bash dev/up.sh        (from the repo root)
set -euo pipefail
cd "$(dirname "$0")/.."

MONGO=gt-dev-mongo
RABBIT=gt-dev-rabbit
DB=guildedthorn_dev

# Prefer podman, fall back to docker
if command -v podman >/dev/null 2>&1; then ENGINE=podman; else ENGINE=docker; fi
echo "==> Using $ENGINE"

# ---------- containers ----------
$ENGINE rm -f $MONGO $RABBIT >/dev/null 2>&1 || true
$ENGINE run -d --name $MONGO  -p 27017:27017 docker.io/library/mongo:8 >/dev/null
$ENGINE run -d --name $RABBIT -p 5672:5672 -p 15672:15672 docker.io/library/rabbitmq:4-management >/dev/null
echo "==> Started $MONGO (27017) and $RABBIT (5672, mgmt ui 15672)"

# ---------- .env ----------
if [ -f .env ]; then
    echo "==> .env already exists, leaving it alone"
else
    JWT_KEY=$(head -c 32 /dev/urandom | base64)
    cat > .env <<EOF
# Generated by dev/up.sh — development values only, do not use in production
MongoDB__ConnectionString=mongodb://localhost:27017
MongoDB__DatabaseName=$DB
RabbitMQ__HostName=localhost
RabbitMQ__Username=guest
RabbitMQ__Password=guest
Jwt__Key=$JWT_KEY
Jwt__Issuer=guildedthorn-dev
Jwt__Audience=guildedthorn-dev
Spotify__ClientId=dev-placeholder
Spotify__ClientSecret=dev-placeholder
Spotify__RedirectUri=https://localhost:7101/api/spotify/callback
EOF
    echo "==> Wrote .env with a fresh JWT key"
fi

# ---------- wait for mongo ----------
echo -n "==> Waiting for MongoDB"
for _ in $(seq 1 30); do
    if $ENGINE exec $MONGO mongosh --quiet --eval 'db.runCommand({ping:1}).ok' >/dev/null 2>&1; then
        echo " — ready"; break
    fi
    echo -n "."; sleep 1
done

# ---------- seed ----------
$ENGINE exec -i $MONGO mongosh --quiet $DB < dev/seed.js

# ---------- markdown test post (content kept readable in dev/markdown-test.md) ----------
MD_B64=$(base64 -w0 dev/markdown-test.md)
$ENGINE exec -i $MONGO mongosh --quiet $DB <<EOF
const content = Buffer.from("$MD_B64", "base64").toString("utf8");
db.BlogPosts.deleteMany({ Title: "The Full Markdown Test" });
db.BlogPosts.insertOne({
    Title: "The Full Markdown Test",
    Content: content,
    CreatedAt: new Date(),
    UpdatedAt: new Date(),
});
print("Seeded markdown test post (" + content.length + " chars)");
EOF

# ---------- gallery placeholder files (served from wwwroot) ----------
mkdir -p wwwroot/images/gallery
# 1x1 red PNG
PNG_B64="iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
for i in 1 2 3; do
    echo "$PNG_B64" | base64 -d > "wwwroot/images/gallery/dev-gallery-$i.png"
done
echo "==> Placed 3 placeholder gallery images in wwwroot/images/gallery/"

cat <<'EOF'

Dev environment is up. Next steps:
  1. Backend:   dotnet run --launch-profile https   (https://localhost:7101)
  2. Frontend:  cd GuildedThorn.com-Frontend && bun run dev
  3. Login as:  thorn / 12345  (owner role)

Tear down with: bash dev/down.sh
EOF
